# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='trabajas_en_educacion',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
    ]
