# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0002_auto_20170815_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='trabajas_en_educacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
    ]
