# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asistentes', '0003_auto_20170815_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentes',
            name='taller',
            field=models.CharField(choices=[('t1', 'Taller 1'), ('t2', 'Taller 2'), ('t3', 'Taller 3'), ('t4', 'Taller 4')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
